version: "3"
services:
    apachephp:
        build: ./dockerfile/
        container_name: pruebaapachephp
        ports:
            - 80:80
        volumes:
            - /home/paco/Documentos/ej5/web:/var/www/html
        depends_on:
            - mariadb
        networks:
            - backend
            - frontend
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: pruebaphp
        ports:
            - 8080:80
        environment:
            PMA_HOST: mariadb
        depends_on:
            - mariadb
        networks:
            - backend
    mariadb:
        image: mariadb:latest
        container_name: mdb
        ports:
            - 3306:3306
        volumes:
            - /home/paco/Documentos/pruebasdocker/ej5/db:/var/lib/mysql
            - /home/paco/Documentos/pruebasdocker/ej5/sql/init.sql:/data/application/init.sql
        command: --init-file /data/application/init.sql
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: testdb
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        networks:
            - backend
networks:
    frontend:
    backend:
