version: "3"
services:
    db:
        image: mysql:latest
        volumes:
            - ./database_files:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: mydb
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        networks:
            - backtier
    wordpress:
        image: wordpress
        ports:
            - 8080:80
        volumes:
            - ./wordpress_files:/var/www/html
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: user
            WORDPRESS_DB_PASSWORD: user
            WORDPRESS_DB_NAME: mydb
        depends_on:
            - db
        networks:
            - backtier
            - fronttier
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 7777:80
        environment:
            PMA_HOST: db
        depends_on:
            - db
        networks:
            - backtier
            - fronttier
networks:
    fronttier:
    backtier:
